name: hello-world
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'doc/**'
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!!!!"
