name: hello-world
on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tag:
        description: 'Apply tag after successfull test run'
        required: true
        type: boolean
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!!!!"
      - name: log-level
        run: |
          echo "Log level: ${{ inputs.logLevel }}"
