name: hello-world
on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tag:
        description: 'Apply tag after successfull test run'
        required: true
        type: boolean
jobs:
  job_1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os_version: [windows-latest, ubuntu-latest]
        node_version: [12, 14, 16]
  
    name: My first job
    runs-on: ${{ matrix.os_version }}
    steps:
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node_version }}
      - run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
      - run: echo '### Love this feature! :medal_sports:' >> $GITHUB_STEP_SUMMARY
      - run: echo '<h1>Great feature!</h1>' >> $GITHUB_STEP_SUMMARY
